-- Supabase schema for C++ course platform (modules/topics + profiles/roles)
-- Run in Supabase SQL Editor.

-- 1) Profiles table for role-based access (admin/user)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  role text not null default 'user',
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy if not exists "profiles_select_own"
on public.profiles for select
using (auth.uid() = id);

create policy if not exists "profiles_update_own"
on public.profiles for update
using (auth.uid() = id);

-- 2) Course modules/topics
create table if not exists public.course_modules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  level text not null,
  sort_order int not null default 0,
  created_at timestamptz default now()
);

create table if not exists public.course_topics (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.course_modules(id) on delete cascade,
  title text not null,
  description text not null,
  type text not null check (type in ('lesson','project','quiz')),
  sort_order int not null default 0,
  content_markdown text,
  created_at timestamptz default now()
);

alter table public.course_modules enable row level security;
alter table public.course_topics enable row level security;

-- If you ran an older version of this schema, remove old public-read policies
drop policy if exists "modules_public_read" on public.course_modules;
drop policy if exists "topics_public_read" on public.course_topics;


-- Helper: is current user admin?
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- Read policies: only authenticated users can read modules/topics
create policy if not exists "modules_read_authenticated"
on public.course_modules for select
using (auth.uid() is not null);

create policy if not exists "topics_read_authenticated"
on public.course_topics for select
using (auth.uid() is not null);

-- Write policies: only admin can insert/update/delete
create policy if not exists "modules_admin_write"
on public.course_modules for all
using (public.is_admin())
with check (public.is_admin());

create policy if not exists "topics_admin_write"
on public.course_topics for all
using (public.is_admin())
with check (public.is_admin());

-- 3) Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, null, 'user')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
